PROGRAM POINTERdef

  REAL, TARGET, DIMENSION(1:10)   :: VECTOR
  REAL, POINTER, DIMENSION(:)     :: POINTER1
  REAL, POINTER                   :: POINTER2

  VECTOR = (/ 1,2,3,4,5,6,7,8,9,10 /)
  
  POINTER1 => VECTOR
  POINTER2 => VECTOR(7)

  PRINT*, "vector", POINTER1
  PRINT*, "scalar", POINTER2

END PROGRAM POINTERdef
